version: "3.8"
services:

  db:
    # image: mcr.microsoft.com/mssql/server:2019-latest
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Express
    volumes:
      - sql1data:/var/opt/mssql
    ports:
      - "1433:1433"
    expose:
      - "1433"

  app:
    build:
      context: .
      dockerfile: ./pckasse_sql_export/Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV:-false}
      target: dev
    environment:
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_USERNAME=${SQL_PASSWORD}
      - SQL_HOST=db
      - SQL_PORT=1433

volumes:
  sql1data: